kind: pipeline
name: webgoat

steps:
  - name: code-analysis
    image: aosapps/drone-sonar-plugin
    settings:
        sonar_host: http://35.188.205.135:9000/
        sonar_token: 77ff9470d9e983100b9b4fa10f119b6b0670e158
