kind: pipeline
name: webgoat

steps:
  - name: code-analysis
    image: aosapps/drone-sonar-plugin
    settings:
      sonar_host: http://35.188.205.135:9000/
      sonar_token: ddcfe0e09800d294563d0f53f23c7beb2fbe438f
    commands:
      - sonar-scanner -Dsonar.projectKey=Neptune:news -Dsonar.sources=. -Dsonar.projectName=WebGoat -Dsonar.projectVersion=1.0 -Dsonar.host.url=http://35.188.205.135:9000 -Dsonar.login=60878847cea1a31d817f0deee3daa7868c431433
