kind: pipeline
name: webgoat

steps:
  - name: code-analysis
    image: aosapps/drone-sonar-plugin
    commands:
      - sonar-scanner -Dsonar.projectKey=webGoat -Dsonar.sources=. -Dsonar.host.url=http://35.188.205.135:9000 -Dsonar.login=ddcfe0e09800d294563d0f53f23c7beb2fbe438f
    settings:
      sonar_host: http://35.188.205.135:9000/
      sonar_token: ddcfe0e09800d294563d0f53f23c7beb2fbe438f
